name: Run dbt Transformations and Terraform

on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 2 AM UTC
  workflow_dispatch:  # Allows manual trigger of the action

jobs:
  setup_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt

      - name: Set up AWS CLI for Terraform
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      - name: Run dbt transformations
        env:
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
        run: |
          cd dbt_project
          dbt run

